"""Redirect owned legacy entry points retained by Desktop to the installed package.

Only exact launchers generated by linux.py setup can be adopted. Original bytes
are kept in a private recovery receipt; custom launchers are never overwritten.
"""
import base64
import json
from pathlib import Path
import shlex

from codex_model_router.platforms.desktop_runtime import DiscoveryError
from codex_model_router.platforms.linux_desktop import atomic_text, fingerprint
from codex_model_router.storage.state_store import atomic_json, file_lock


def redirect_launchers(root, legacy, bridge, monitor, backend, desktop=None):
    root, legacy = Path(root).resolve(), Path(legacy).resolve()
    receipt = root / 'state/legacy-launchers.json'
    paths = {name: legacy / 'dist' / name for name in ('codex-router', 'codex-monitor-linux', 'codex-desktop')}
    targets = {'codex-router': Path(bridge), 'codex-monitor-linux': Path(monitor),
               'codex-desktop': Path(desktop) if desktop is not None else Path(bridge).parent / 'codex-desktop'}
    if any(not path.is_file() or path.is_symlink() for path in paths.values()):
        raise DiscoveryError('Los lanzadores anteriores no son archivos propios compatibles; se han conservado.')
    with file_lock(root / 'state/legacy-launchers.lock'):
        previous_record = json.loads(receipt.read_text()) if receipt.exists() else None
        if previous_record and (previous_record.get('legacy') != str(legacy) or previous_record.get('schema') != 1):
            raise DiscoveryError('Existe un traspaso de otra instalación; se ha conservado.')
        cfg = json.loads((legacy / 'config.local.json').read_text(encoding='utf-8-sig'))
        python = cfg.get('python', '/usr/bin/python3')
        expected = {
            'codex-router': '#!/bin/sh\nexport PERSONAL_CODEX_ROUTER_CONFIG=' + shlex.quote(str(legacy / 'config.local.json')) +
                '\nexport PYTHONUTF8=1\nexec ' + shlex.quote(python) + ' ' + shlex.quote(str(legacy / 'router.py')) + ' "$@"\n',
            'codex-monitor-linux': '#!/bin/sh\nexec ' + shlex.quote(python) + ' ' + shlex.quote(str(legacy / 'monitor_linux.py')) + ' "$@"\n',
            'codex-desktop': '#!/bin/sh\nexec ' + shlex.quote(python) + ' ' + shlex.quote(str(legacy / 'linux.py')) + ' launch-native -- "$@"\n'}
        before, entries, desired = {}, {}, {}
        for name, path in paths.items():
            body = path.read_bytes()
            saved = previous_record.get('entries', {}).get(name) if previous_record else None
            if saved:
                if saved.get('path') != str(path) or fingerprint(body) not in (saved.get('installed_sha256'), saved.get('original_sha256')):
                    raise DiscoveryError('Un lanzador anterior fue modificado externamente; se ha conservado.')
                original = base64.b64decode(saved['original'])
                mode = saved['mode']
            else:
                if body != expected[name].encode():
                    raise DiscoveryError('Un lanzador anterior es personalizado; se ha conservado.')
                original, mode = body, path.stat().st_mode & 0o777
            before[name] = (body, path.stat().st_mode & 0o777)
            clear = 'unset CODEX_CLI_PATH PERSONAL_CODEX_ROUTER_CONFIG PERSONAL_CODEX_ROUTER_CODE_ROOT PERSONAL_CODEX_ROUTER_STATE PERSONAL_CODEX_ROUTER_ROOT\n'
            text = '#!/bin/sh\n' + clear
            text += 'if [ -x ' + shlex.quote(str(targets[name])) + ' ]; then\n'
            text += '  export PERSONAL_CODEX_ROUTER_ROOT=' + shlex.quote(str(root)) + '\n'
            text += '  exec ' + shlex.quote(str(targets[name])) + ' "$@"\nfi\n'
            if name == 'codex-router': text += 'exec ' + shlex.quote(str(backend)) + ' "$@"\n'
            elif name == 'codex-desktop': text += 'exec "$@"\n'
            else: text += 'exit 0\n'
            desired[name] = text
            entries[name] = {'path': str(path), 'original': base64.b64encode(original).decode(),
                'original_sha256': fingerprint(original), 'mode': mode, 'installed_sha256': fingerprint(text.encode())}
        record = {'schema': 1, 'legacy': str(legacy), 'status': 'preparing', 'entries': entries}
        atomic_json(receipt, record)
        try:
            for name, path in paths.items():
                # Refuse concurrent source setup/customization detected since validation.
                if path.read_bytes() != before[name][0]:
                    raise DiscoveryError('El lanzador cambió durante el traspaso; se ha conservado.')
                atomic_text(path, desired[name], before[name][1])
            record['status'] = 'redirected'
            atomic_json(receipt, record)
        except Exception:
            for name, path in paths.items():
                if path.is_file() and fingerprint(path.read_bytes()) == entries[name]['installed_sha256']:
                    atomic_text(path, before[name][0].decode(), before[name][1])
            if previous_record: atomic_json(receipt, previous_record)
            else: receipt.unlink(missing_ok=True)
            raise
        return {'redirected': True, 'launchers': len(entries)}
